export const REORDER = 'constructor/reorder'
export const MOVE_COLOR = 'constructor/move_color'
export const MOVE_INTO_MINUSPHRASES = 'constructor/move_into_minusphrases'
export const MOVE_INTO_GROUP = 'constructor/move_into_group'
export const SELECT_KEYWORD = 'constructor/select_keyword'
export const TOGGLE_MODAL_MINUSPHRASES = 'constructor/toggle_modal_minusphrases'
export const TOGGLE_MODAL_GROUPS = 'constructor/toggle_modal_groups'

export const ADD_WORD = 'constructor/select_word'
export const DELETE_WORD = 'constructor/delete_word'
export const DELETE_KEYWORD = 'constructor/delete_keyword'
export const ADD_INTO_MINUSPHRASES = 'constructor/add_into_minusphrases'