export const REORDER = 'constructor/reorder'
export const MOVE_COLOR = 'constructor/move_color'
export const MOVE_INTO_MINUSPHRASES = 'constructor/move_into_minusphrases'
export const MOVE_INTO_GROUP = 'constructor/move_into_group'
export const SELECT_KEYWORD = 'constructor/select_keyword'
export const TOGGLE_MODAL = 'constructor/modal'